name = "python-mastery"
main = "backend/worker.py"
compatibility_date = "2024-09-23"
compatibility_flags = ["python_workers"]

[assets]
directory = "frontend/dist/frontend/browser"
binding = "ASSETS"
